- name: Add apache2 user to ssl-cert group
  user: name=apache2 groups=ssl-cert

- name: Remove Default site configuration
  file: path=/etc/apache2/sites-enabled/000-default.conf state=absent

- name: Remove Index file
  file: path=/var/www/html/index.html state=absent

- name: Configure HTTPS only listen port
  copy:
    src: roles/apache2/files/ports.conf
    dest: /etc/apache2/ports.conf

- name: Install IdP Virtualhost configuration
  copy:
    src: roles/apache2/files/idp.conf
    dest: /etc/apache2/sites-available/idp.example.org.conf

- name: Install SP Virtualhost configuration
  template:
    src: roles/apache2/files/sp.conf
    dest: /etc/apache2/sites-available/sp.example.org.conf


- name: Dirs for IdP and SP Virtualhosts
  file: name={{ item }} state=directory
  with_items:
    - /var/log/apache2/idp.example.org
    - /var/log/apache2/sp.example.org
    - /var/www/html/sp.example.org
    - /var/www/html/sp.example.org/secure
    - /var/www/html/idp.example.org
    - /var/www/css

- name: Install IdP Index file 
  copy:
    src: roles/apache2/files/idp-index.html
    dest: /var/www/html/idp.example.org/index.html

- name: Install SP Index file 
  copy:
    src: roles/apache2/files/sp-index.html
    dest: /var/www/html/sp.example.org/index.html

- name: Install SP Secure Location Index file 
  copy:
    src: roles/apache2/files/sp-secure-index.html
    dest: /var/www/html/sp.example.org/secure/index.html

- name: Install Bootstrap Min CSS 
  copy:
    src: roles/apache2/files/bootstrap.min.css
    dest: /var/www/css/bootstrap.min.css

- name: Enable proxy_ajp and ssl modules
  apache2_module: name={{ item }} state=present
  with_items:
    - proxy_ajp
    - ssl

- name: Enable IdP Virtualhost
  command: a2ensite idp.example.org.conf
  args:
    creates: /etc/apache2/sites-enabled/idp.example.org.conf

- name: Enable SP Virtualhost
  command: a2ensite sp.example.org.conf
  args:
    creates: /etc/apache2/sites-enabled/sp.example.org.conf

- name: Restart Apache2
  service: name=apache2 state=restarted enabled=yes

